title: Qishan Pan's Homepage
page-top-title: Qishan Pan
top-section-bg-text: Power Electronics
home-subtitle: Qishan Pan&ensp;|&ensp;潘其山
copyright-text: '&copy; Qishan Pan 2025. All Rights Reserved.'
